version: '3'

services:
  server:
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
      - STAGE=development
    command: npm run start:dev
